package com.appvet.entities;
// Generated 26/10/2018 10:24:52 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name = "agenda", schema = "base_vet")
public class Agenda implements java.io.Serializable {

	private Integer idagenda;
	private Usuario usuario;

	public Agenda() {
	}

	public Agenda(Usuario usuario) {
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idagenda", unique = true, nullable = false)
	public Integer getIdagenda() {
		return this.idagenda;
	}

	public void setIdagenda(Integer idagenda) {
		this.idagenda = idagenda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
