package com.appvet.entities;
// Generated 26/10/2018 10:24:52 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cita generated by hbm2java
 */
@Entity
@Table(name = "cita", schema = "base_vet")
public class Cita implements java.io.Serializable {

	private Integer idcita;
	private Mascota mascota;
	private Date fechacita;
	private String lugar;
	private String especificaciones;

	public Cita() {
	}

	public Cita(Mascota mascota, Date fechacita, String lugar, String especificaciones) {
		this.mascota = mascota;
		this.fechacita = fechacita;
		this.lugar = lugar;
		this.especificaciones = especificaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcita", unique = true, nullable = false)
	public Integer getIdcita() {
		return this.idcita;
	}

	public void setIdcita(Integer idcita) {
		this.idcita = idcita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmascota")
	public Mascota getMascota() {
		return this.mascota;
	}

	public void setMascota(Mascota mascota) {
		this.mascota = mascota;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechacita", length = 10)
	public Date getFechacita() {
		return this.fechacita;
	}

	public void setFechacita(Date fechacita) {
		this.fechacita = fechacita;
	}

	@Column(name = "lugar", length = 45)
	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	@Column(name = "especificaciones", length = 300)
	public String getEspecificaciones() {
		return this.especificaciones;
	}

	public void setEspecificaciones(String especificaciones) {
		this.especificaciones = especificaciones;
	}

}
