package com.appvet.entities;
// Generated 26/10/2018 10:24:52 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallehistoria generated by hbm2java
 */
@Entity
@Table(name = "detallehistoria", schema = "base_vet")
public class Detallehistoria implements java.io.Serializable {

	private Integer iddetallehistoria;
	private Historiaclinica historiaclinica;
	private String motivoconsulta;
	private BigDecimal temperatura;
	private Integer frecuenciacardiaca;
	private Integer frecuenciarespiratoria;
	private BigDecimal peso;
	private String sintomas;
	private String anamnesis;
	private String diagnosticopresuntivo;
	private String pruebasclinicas;
	private String diagnosticodefinitivo;
	private String plantratamiento;
	private String observaciones;

	public Detallehistoria() {
	}

	public Detallehistoria(Historiaclinica historiaclinica, String motivoconsulta, BigDecimal temperatura,
			Integer frecuenciacardiaca, Integer frecuenciarespiratoria, BigDecimal peso, String sintomas,
			String anamnesis, String diagnosticopresuntivo, String pruebasclinicas, String diagnosticodefinitivo,
			String plantratamiento, String observaciones) {
		this.historiaclinica = historiaclinica;
		this.motivoconsulta = motivoconsulta;
		this.temperatura = temperatura;
		this.frecuenciacardiaca = frecuenciacardiaca;
		this.frecuenciarespiratoria = frecuenciarespiratoria;
		this.peso = peso;
		this.sintomas = sintomas;
		this.anamnesis = anamnesis;
		this.diagnosticopresuntivo = diagnosticopresuntivo;
		this.pruebasclinicas = pruebasclinicas;
		this.diagnosticodefinitivo = diagnosticodefinitivo;
		this.plantratamiento = plantratamiento;
		this.observaciones = observaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddetallehistoria", unique = true, nullable = false)
	public Integer getIddetallehistoria() {
		return this.iddetallehistoria;
	}

	public void setIddetallehistoria(Integer iddetallehistoria) {
		this.iddetallehistoria = iddetallehistoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idhistoria")
	public Historiaclinica getHistoriaclinica() {
		return this.historiaclinica;
	}

	public void setHistoriaclinica(Historiaclinica historiaclinica) {
		this.historiaclinica = historiaclinica;
	}

	@Column(name = "motivoconsulta", length = 100)
	public String getMotivoconsulta() {
		return this.motivoconsulta;
	}

	public void setMotivoconsulta(String motivoconsulta) {
		this.motivoconsulta = motivoconsulta;
	}

	@Column(name = "temperatura", precision = 5)
	public BigDecimal getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(BigDecimal temperatura) {
		this.temperatura = temperatura;
	}

	@Column(name = "frecuenciacardiaca")
	public Integer getFrecuenciacardiaca() {
		return this.frecuenciacardiaca;
	}

	public void setFrecuenciacardiaca(Integer frecuenciacardiaca) {
		this.frecuenciacardiaca = frecuenciacardiaca;
	}

	@Column(name = "frecuenciarespiratoria")
	public Integer getFrecuenciarespiratoria() {
		return this.frecuenciarespiratoria;
	}

	public void setFrecuenciarespiratoria(Integer frecuenciarespiratoria) {
		this.frecuenciarespiratoria = frecuenciarespiratoria;
	}

	@Column(name = "peso", precision = 5)
	public BigDecimal getPeso() {
		return this.peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	@Column(name = "sintomas", length = 150)
	public String getSintomas() {
		return this.sintomas;
	}

	public void setSintomas(String sintomas) {
		this.sintomas = sintomas;
	}

	@Column(name = "anamnesis", length = 300)
	public String getAnamnesis() {
		return this.anamnesis;
	}

	public void setAnamnesis(String anamnesis) {
		this.anamnesis = anamnesis;
	}

	@Column(name = "diagnosticopresuntivo", length = 300)
	public String getDiagnosticopresuntivo() {
		return this.diagnosticopresuntivo;
	}

	public void setDiagnosticopresuntivo(String diagnosticopresuntivo) {
		this.diagnosticopresuntivo = diagnosticopresuntivo;
	}

	@Column(name = "pruebasclinicas", length = 300)
	public String getPruebasclinicas() {
		return this.pruebasclinicas;
	}

	public void setPruebasclinicas(String pruebasclinicas) {
		this.pruebasclinicas = pruebasclinicas;
	}

	@Column(name = "diagnosticodefinitivo", length = 300)
	public String getDiagnosticodefinitivo() {
		return this.diagnosticodefinitivo;
	}

	public void setDiagnosticodefinitivo(String diagnosticodefinitivo) {
		this.diagnosticodefinitivo = diagnosticodefinitivo;
	}

	@Column(name = "plantratamiento", length = 300)
	public String getPlantratamiento() {
		return this.plantratamiento;
	}

	public void setPlantratamiento(String plantratamiento) {
		this.plantratamiento = plantratamiento;
	}

	@Column(name = "observaciones", length = 200)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
