package com.appvet.entities;
// Generated 26/10/2018 10:24:52 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Historiaclinica generated by hbm2java
 */
@Entity
@Table(name = "historiaclinica", schema = "base_vet")
public class Historiaclinica implements java.io.Serializable {

	private Integer idhistoria;
	private Mascota mascota;
	private Set<Detallehistoria> detallehistorias = new HashSet<Detallehistoria>(0);

	public Historiaclinica() {
	}

	public Historiaclinica(Mascota mascota, Set<Detallehistoria> detallehistorias) {
		this.mascota = mascota;
		this.detallehistorias = detallehistorias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idhistoria", unique = true, nullable = false)
	public Integer getIdhistoria() {
		return this.idhistoria;
	}

	public void setIdhistoria(Integer idhistoria) {
		this.idhistoria = idhistoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmascota")
	public Mascota getMascota() {
		return this.mascota;
	}

	public void setMascota(Mascota mascota) {
		this.mascota = mascota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "historiaclinica")
	public Set<Detallehistoria> getDetallehistorias() {
		return this.detallehistorias;
	}

	public void setDetallehistorias(Set<Detallehistoria> detallehistorias) {
		this.detallehistorias = detallehistorias;
	}

}
