package com.appvet.entities;
// Generated 26/10/2018 10:24:52 PM by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "pago", schema = "base_vet")
public class Pago implements java.io.Serializable {

	private Integer idpago;
	private Cliente cliente;
	private Usuario usuario;
	private Date fechapago;
	private BigDecimal subtotal;
	private BigDecimal descuento;
	private BigDecimal total;
	private Set<Detallepago> detallepagos = new HashSet<Detallepago>(0);

	public Pago() {
	}

	public Pago(Cliente cliente, Usuario usuario, Date fechapago, BigDecimal subtotal, BigDecimal descuento,
			BigDecimal total, Set<Detallepago> detallepagos) {
		this.cliente = cliente;
		this.usuario = usuario;
		this.fechapago = fechapago;
		this.subtotal = subtotal;
		this.descuento = descuento;
		this.total = total;
		this.detallepagos = detallepagos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpago", unique = true, nullable = false)
	public Integer getIdpago() {
		return this.idpago;
	}

	public void setIdpago(Integer idpago) {
		this.idpago = idpago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechapago", length = 10)
	public Date getFechapago() {
		return this.fechapago;
	}

	public void setFechapago(Date fechapago) {
		this.fechapago = fechapago;
	}

	@Column(name = "subtotal", precision = 7)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "descuento", precision = 7)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "total", precision = 7)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pago")
	public Set<Detallepago> getDetallepagos() {
		return this.detallepagos;
	}

	public void setDetallepagos(Set<Detallepago> detallepagos) {
		this.detallepagos = detallepagos;
	}

}
